tree = """
Algebra (ALG)
    Equations and Expressions (EE)
        Evaluate Expression with Known Variables (EVAL)
        Solve Equation (SE)
        Solve a 2x2 System of Linear or Nonlinear Equations by Substitution (SSES)

    Exponents (EX)
        Exponent (EX)
        Rational Exponent (RE)

    Factorial (F)

    Function (FUN)
        Function Call (FC)
        Find Roots (FR)
        Find y-intercept (FYI)
        Factor Function (FF)
        Expand Function (EF)

    Graphing (G)
        Coordinate (C)
        Function (F)
        Multiple Functions (MF)

    Imaginary (I)
        Raise j to the nth Power (JN)
        Evaluate an Imaginary Expression (EIE)

    Line (L)
        Slope (S)
        Find Equation of Line in Slope-intercept Form (SIF)

    Logarithm (LOG)

    Matrices (M)
        Add Matrices (AM)
        Create Matrices (CM)
        Display Matrices (DM)
        Multiply by a Scalar (MS)
        Multiply Matrices (MM)
        Find Determinant (FD)
        Inverse (INV)
        Transpose (TP)

    Primality Test (PT)

    Quadratic(Q)
        Quadratic Function Call (QFC)
        Find Discriminant (FD)
        Find Roots (FR)
        Find y-intercept (FYI)
        Find Vertex (FV)
        Factor Quadratic (FQ)
        Expand Quadratic (EQ)

    Radicals (RD)
        Find nth Root (FNR)

    Rounding (R)
        Regular Rounding (RR)
        Round to Ceiling (RC)
        Round to Floor (RF)

    Trig Functions (TF)
        Sine (SIN)
        Cosine (COS)
        Tangent (TAN)
        Arcsine (ASIN)
        Arccosine (ACOS)
        Arctangent (ATAN)

Arts and Design (AD)
    Color Codes (CC)
        Convert Hexadecimal to RGB (HR)
        Convert RGB to Hexadecimal (RH)
        Show Color by RGB Value (SC)

    Metronome (M)

    Pixels per Inch Calculator (PPI)

Chemistry (CHEM)
    Temperature Conversions (TC)
        Celsius to Fahrenheit (CF)
        Celsius to Kelvin (CK)
        Fahrenheit to Celsius (FC)
        Fahrenheit to Kelvin (FK)
        Kelvin to Celsius (KC)
        Kelvin to Fahrenheit (KF)

Computer Science (CS)
    Base Conversion (BC)
          Binary to Octal (BO)
          Binary to Decimal (BD)
          Binary to Hexadecimal (BH)
          Octal to Binary (OB)
          Octal to Decimal (OD)
          Octal to Hexadecimal (OH)
          Decimal to Binary (DB)
          Decimal to Octal (DO)
          Decimal to Hexadecimal (DH)
          Hexadecimal to Binary (HB)
          Hexadecimal to Octal (HO)
          Hexadecimal to Decimal (HD)
          Base N to Decimal (ND)
          Decimal to Base N (DN)
          Base N to Base M (NM)

    Sorting Algorithms (SRTA)
        Bubble Sort (BS)
            Generate Custom List (GCL)
            Generate Random List (GRL)
        Insertion Sort (IS)
            Generate Custom List (GCL)
            Generate Random List (GRL)
        Selection Sort (SS)
            Generate Custom List (GCL)
            Generate Random List (GRL)
        Quicksort (QS)
            Generate Custom List (GCL)
            Generate Random List (GRL)

Constants (CON)
    Value of Pi (PI)
    Value of Euler\'s Number (E)

Geometry (GEOM)
    Angle Measure Conversion (AMC)
        Radians to Degrees (RD)
        Degrees to Radians (DR)

    Circle (C)
        Find Area (A)
        Find the Area of a Sector (AS)
        Find Circumference (C)
        Find Diameter (D)
        Find Radius (R)

    Distance (D)
        Two-Dimensional Distance (2D)
        Three-Dimensional Distance (3D)

    Midpoint (M)
        One-Dimensional Midpoint (1D)
        Two-Dimensional Midpoint (2D)
        Three-Dimensional Midpoint (3D)
        N-Dimensional Midpoint (ND)
        N-Dimensional Midpoint with M Points (NDMP)

    Pythagorean Theorem (PT)
        Find the Hypotenuse (HYPO)
        Find Leg A (LA)
        Find Leg B (LB)

    Rectangle (R)
        Find Area (A)
        Find Diagonal (D)
        Find Length (L)
        Find Perimeter (P)
        Find Width (W)

    Rectangular Prism (RP)
        Find Height (H)
        Find Length (L)
        Find Space Diagonal (SD)
        Find Surface Area (SA)
        Find Volume (V)
        Find Width (W)

    Regular Polygon (POLY)
        Find Interior Angle Measure (IAM)
        Find Interior Angle Sum (IAS)
        Find Exterior Angle Measure (EAM)
        Find Exterior Angle Sum (EAS)
        Find Area (A)
        Find Perimeter (P)

    Rhombus (RH)
        Find Area (A)
        Find Perimeter (P)
        Find Side Length (SL)
        Find Diagonal Q (DQ)
        Find Diagonal P (DP)

    Sphere (SPH)
        Find Volume (V)
        Find Radius (R)
        Find Diameter (D)
        Find Surface Area (SA)

    Trapezoid (TRAP)
        Find Area (A)
        Find Height (H)
        Find Base A (BA)
        Find Base B (BB)
        Find Perimeter (P)
        Find Side C (SC)
        Find Side D (SD)

    Triangle (T)
        Find Area (A)
        Find Base (B)
        Find Height (H)
        Find Perimeter (P)
        Find Third Angle Measure (TAM)

    Trig Definitions (TD)
        Find Opposite Given Hypotenuse (OH)
        Find Adjacent Given Hypotenuse (AH)
        Find Opposite Given Adjacent (OA)
        Find Hypotenuse Given Opposite (HO)
        Find Hypotenuse Given Adjacent (HA)
        Find Adjacent Given Opposite (AO)
        Find Theta Given Hypotenuse and Opposite (THO)
        Find Theta Given Hypotenuse and Adjacent (THA)
        Find Theta Given Opposite and Adjacent (TOA)

Sort List by Data Type (SLDT)
    Integers (I)
        Generate Custom List (GCL)
        Generate Random List (GRL)

    Floats/Decimals (F)
        Generate Custom List (GCL)
        Generate Random List (GRL)

    Strings/Text (S)
        Generate Custom List (GCL)
        Generate Random List (GRL)

Standard Calculator (SC)

Tree (TREE)

Update Check (UC)
"""